server:
  port: 8989

spring:
  datasource:
    # 数据库连接池的类型HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root # 远程密码：Zhw521..
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  redis:
    host: 192.168.6.60
    port: 6379
    password: 123456
    database: 0  # redis数据库索引 有16个数据库  默认使用第一个
  jackson:
    # Date类型的字段在序列化成JSON字符串时，需要考虑两个点，
    # 分别是格式和时区。本项目使用JSON序列化框架为Jackson
    # date-format: yyyy-MM-dd HH:mm:ss # 格式
    # 推荐格式按照字段单独配置，时区全局配置
    time-zone: GMT+8 # 时区
    # 确保@JsonValue有效
    # default-property-inclusion: non_null
  servlet:
    multipart:
      # 设置单个文件的最大大小（例如 10MB）
      max-file-size: 10MB
      # 设置总请求的最大大小（例如 20GB）
      max-request-size: 20GB
#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-enums-package: com.zhw.blog.model.enums


jwt:
  secret: zhw  # 密钥，用于签名和验证 JWT
  expiration: 86400000  # 过期时间（毫秒），例如 86400000 表示 24 小时
  header: Authorization  # HTTP 请求头名称，默认为 Authorization
  prefix: Bearer  #2 JWT 前缀，默认为 Bearer
  issuer: zhw  # 签发者
  algorithm: AES #  生成加密后的秘钥算法
  # token-validity-in-seconds: 86400  # 令牌有效期（秒）
  # token-validity-in-seconds-for-remember-me: 2592000  # 记住我模式下的令牌有效期（秒）

# 权限配置
auth:
  interceptor:
    add-path-patterns: /admin/**
    exclude-path-patterns: /admin/login/**